name: Call Collection Run
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  install-git-lfs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install
 
  call-workflow:
    uses: digital-land/collection-template/.github/workflows/callable_run.yml@main
    secrets: inherit